### PR TITLE
egcd algorithm improvement

### PR DESCRIPTION
**Pull request by reversebrain**
I modified the egcd algorithm with a more efficient one avoiding recursion depth errors that I encountered yesterday. Use this values as example with the original and the modified egcd algorithm:

```
>>> n1 = 571230664420414536010658335240650474708178830908478267303809243874544614572677931738564969631108410892825598197486100422395258721792097296352236400453767433855171326258850580406118721211758856886425221713375718678602924777909908417968517364070600923396491728610936061154753196249653057869501799394342114668754879619727788767297662721041502212187328357312697013651820752853728157706193796151319419061858393431144129401422662283403839922767870572595643177142983167744121366360997896645903405186036305997490267959100034593348524397026675271843941370324910257159637798740635393234381431761623810153174684916408586207576217899652907974665184037984591595324872554374431039266406980206405294500984595881883358267961023604143485042232818788421699552307349536542680305072000213480031105524258682516571716303425006147266944864690818527775048130501514668576724097693916831988445712531256724398018080493490910389197974303164334183362933349578755030058173827634802410729003153069553588094399670922834097148880443754388016971489394287966561582975792753093237681939241127182841768504213924761113548379431449156621733054285939099805622979954128578271934335619408106480389349171183194823277972632964996654956427962324765844790465218543253276456552121
>>> n2 = 431351651838527802207037885635247025268306381514599054662373243738700643220615842016187396420925967597550532689806871732470372055640155670155046416761907604797056013084951897531202531890949670420573885170153915699289221618345229834131227863268965091928277820354791364127140580300699798052518395803046450212475008252674778736401058002553816657645455424912640102054950927370445770184880908078861264463171934472384479997636144232668556202589681036761617293357791646120864187471186758012105275889667053426747106302844458685267399216940322928550073193200455850521134664260229769119830168612122478003696213402144031478785911551028169340865305929378388829847625151290619796125343887330831344130345776965110023251914764319207448579182455400837346267355268871066930107789009809940727384345277598187607780629154115360924857407833371284913621571274983644719483625481853290951303034354549597344472463483142878595541804995927822260336805828609638193316111974207075416043926377682061018590657115248568911386650522111666195904275542775579031153165526696913346356046223824660341679161802408252403434479125361755663765756444333554612966536669805938075660532926431455355198252679465223018552745361488689282479006557407620644323916464436596259806136917
>>> c1 = 341836120102909874868579624744535142745673332664237018676343001828512456841818702993672960036466286404162516556872556642718335017105333220014757659187812903082556848774045841278248049275314799455502878226327107243494439020459433429505564101497402531900927949903302402450851578273717106165632226499420950582298400414550175957081493152672859671634595515847674623323452248358048769894673622535751918167549896849828283249445319449699958294915880087598088184937123342286115368597674406225458861349541604197808757912441869529143217173931226191982700026172244173898013463892767283068457210426719556778839312587390646684952182485020415764422889602817795188445372502873049905509848680602356249468261257862916995178202263738892387885552598980669012585669971023684918855992972432309170359508178293570093845145846675438016212123833825418697581523551214235311879591690458037177000964220105477462616368912428839901151171743810760299924266536913507855127130729005887686781991234628903144161934316689567135843105994643831785019764655633371567562211570615677704840996184777667022178820709746122901770749162340940024414976836263655031174548189886978259967010148754675749793256368247216281468370329038999576415150202414264675514812780342214757750415465
>>> c2 = 96150929170737241090249647700057421926877468755494394158771537480926879715902501359054598261092335102295402780928159568694837168595250653360511222602164550644615448867684551614543966829218997335786789418234321242722107757101664151490170736902489142687115716849530057503756308886279658245268585621132889072519672048650594716219969087856280893445392412929961513288335844377789944596168171325235299163421796686718668737749379218317528709023561495246406153257563800178339207009017105854833744267712652697632740870339053393523801107829803506781697371976671510187537542378047282092377793172223347820740666056540518425305749668146964979848472012478654015661346999145066739264026153827068036391245567970218878269216661254631823416123534642151579370581432686206316981008523924704627091336803465779571089823279580593499172325535797565024428313545234152955079805213959468134330488091053643900235067019182445820100860711776467151716059428574518438992370613285074257671172860330824649372175220228570301596423723811857670493999818550335418920267284055173428543762523394576858129338459913071119304523220472050461316989878998867758394488783998338238849386780640501867307854268111225236019443598745383671617163866659260197226770757626250333185941847
>>> e = 65537
```
Also this type of attack is called "common factor attack" and not "common exponent attack".

### CODE REVIEW

**Comment by X-Vector** [comment]
You are right , Thanks <3

**Comment by reversebrain** [comment]
Approve the pull request to confirm the changes.

**Review by X-Vector — APPROVED** [review]

**Review by X-Vector — APPROVED** [review]

**Review by reversebrain — COMMENTED** [review]
I don't know what triggered the warning about conflicts, by the way the code seems ok.

**Review by reversebrain — COMMENTED** [review]
These changes are ok for me.

**Review by reversebrain — COMMENTED** [review]
I fixed the import for `RSA_common_factor` from `Attack.py` that I didn't rename

**Pull request closed without merging**
